name: Deploy to Heroku

on:
  push:
    branches:
      - production
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Remove composer lock
        run: rm -f composer.lock

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install Node.js dependencies
        run: npm install

      - name: Build assets with Vite
        run: npm run build

      - name: Create .env.testing file
        run: |
          cp .env.example .env.testing
          php artisan jwt:secret --env=testing
          echo "DB_CONNECTION=sqlite" >> .env.testing
          echo "DB_DATABASE=:memory:" >> .env.testing
          php artisan key:generate --env=testing
      - name: Run migrations for testing
        run: php artisan migrate --env=testing --force

      - name: Run Unit tests -- feature tests
        run: php artisan test --testsuite=Feature

      - name: Run Unit tests -- unit tests
        run: php artisan test --env=testing --testsuite=Unit

      - name: Set up Git user identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Fetch from Heroku
        if: github.ref == 'refs/heads/production'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/vending-machine-system.git
          git fetch heroku

      - name: Continue rebase if necessary
        if: github.ref == 'refs/heads/production'
        run: git rebase --continue || echo "No rebase needed"

      - name: Deploy to Heroku (Production)
        if: github.ref == 'refs/heads/production' && success()
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git checkout -b main
          git fetch --all --unshallow
          git push heroku main --force
